[input]
base_directory = "test/essays"
files = [
    { path = "essays/essay01.txt", url="essays/essay01.txt", title="essay01.txt" },
    { path = "essays/essay02.txt", url="essays/essay02.txt", title="essay02.txt" },
    { path = "essays/essay03.txt", url="essays/essay03.txt", title="essay03.txt" },
    { path = "essays/essay04.txt", url="essays/essay04.txt", title="essay04.txt" },
    { path = "essays/essay05.txt", url="essays/essay05.txt", title="essay05.txt" },
    { path = "essays/essay06.txt", url="essays/essay06.txt", title="essay06.txt" },
    { path = "essays/essay07.txt", url="essays/essay07.txt", title="essay07.txt" },
    { path = "essays/essay08.txt", url="essays/essay08.txt", title="essay08.txt" },
    { path = "essays/essay09.txt", url="essays/essay09.txt", title="essay09.txt" },
    { path = "essays/essay10.txt", url="essays/essay10.txt", title="essay10.txt" },
    { path = "essays/essay11.txt", url="essays/essay11.txt", title="essay11.txt" },
    { path = "essays/essay12.txt", url="essays/essay12.txt", title="essay12.txt" },
    { path = "essays/essay13.txt", url="essays/essay13.txt", title="essay13.txt" },
    { path = "essays/essay14.txt", url="essays/essay14.txt", title="essay14.txt" },
    { path = "essays/essay15.txt", url="essays/essay15.txt", title="essay15.txt" },
    { path = "essays/essay16.txt", url="essays/essay16.txt", title="essay16.txt" },
    { path = "essays/essay17.txt", url="essays/essay17.txt", title="essay17.txt" },
    { path = "essays/essay18.txt", url="essays/essay18.txt", title="essay18.txt" },
    { path = "essays/essay19.txt", url="essays/essay19.txt", title="essay19.txt" },
    { path = "essays/essay20.txt", url="essays/essay20.txt", title="essay20.txt" },
    { path = "essays/essay21.txt", url="essays/essay21.txt", title="essay21.txt" },
    { path = "essays/essay22.txt", url="essays/essay22.txt", title="essay22.txt" },
    { path = "essays/essay23.txt", url="essays/essay23.txt", title="essay23.txt" },
    { path = "essays/essay24.txt", url="essays/essay24.txt", title="essay24.txt" },
    { path = "essays/essay25.txt", url="essays/essay25.txt", title="essay25.txt" },
    { path = "essays/essay26.txt", url="essays/essay26.txt", title="essay26.txt" },
    { path = "essays/essay27.txt", url="essays/essay27.txt", title="essay27.txt" },
    { path = "essays/essay28.txt", url="essays/essay28.txt", title="essay28.txt" },
    { path = "essays/essay29.txt", url="essays/essay29.txt", title="essay29.txt" },
    { path = "essays/essay30.txt", url="essays/essay30.txt", title="essay30.txt" },
    { path = "essays/essay31.txt", url="essays/essay31.txt", title="essay31.txt" },
    { path = "essays/essay32.txt", url="essays/essay32.txt", title="essay32.txt" },
    { path = "essays/essay33.txt", url="essays/essay33.txt", title="essay33.txt" },
    { path = "essays/essay34.txt", url="essays/essay34.txt", title="essay34.txt" },
    { path = "essays/essay35.txt", url="essays/essay35.txt", title="essay35.txt" },
    { path = "essays/essay36.txt", url="essays/essay36.txt", title="essay36.txt" },
    { path = "essays/essay37.txt", url="essays/essay37.txt", title="essay37.txt" },
    { path = "essays/essay38.txt", url="essays/essay38.txt", title="essay38.txt" },
    { path = "essays/essay39.txt", url="essays/essay39.txt", title="essay39.txt" },
    { path = "essays/essay40.txt", url="essays/essay40.txt", title="essay40.txt" },
    { path = "essays/essay41.txt", url="essays/essay41.txt", title="essay41.txt" },
    { path = "essays/essay42.txt", url="essays/essay42.txt", title="essay42.txt" },
    { path = "essays/essay43.txt", url="essays/essay43.txt", title="essay43.txt" },
    { path = "essays/essay44.txt", url="essays/essay44.txt", title="essay44.txt" },
    { path = "essays/essay45.txt", url="essays/essay45.txt", title="essay45.txt" },
    { path = "essays/essay46.txt", url="essays/essay46.txt", title="essay46.txt" },
    { path = "essays/essay47.txt", url="essays/essay47.txt", title="essay47.txt" },
    { path = "essays/essay48.txt", url="essays/essay48.txt", title="essay48.txt" },
    { path = "essays/essay49.txt", url="essays/essay49.txt", title="essay49.txt" },
    { path = "essays/essay50.txt", url="essays/essay50.txt", title="essay50.txt" },
    { path = "essays/essay51.txt", url="essays/essay51.txt", title="essay51.txt" },
    { path = "essays/essay52.txt", url="essays/essay52.txt", title="essay52.txt" },
    { path = "essays/essay53.txt", url="essays/essay53.txt", title="essay53.txt" },
    { path = "essays/essay54.txt", url="essays/essay54.txt", title="essay54.txt" },
    { path = "essays/essay55.txt", url="essays/essay55.txt", title="essay55.txt" },
    { path = "essays/essay56.txt", url="essays/essay56.txt", title="essay56.txt" },
    { path = "essays/essay57.txt", url="essays/essay57.txt", title="essay57.txt" },
    { path = "essays/essay58.txt", url="essays/essay58.txt", title="essay58.txt" },
    { path = "essays/essay59.txt", url="essays/essay59.txt", title="essay59.txt" },
    { path = "essays/essay60.txt", url="essays/essay60.txt", title="essay60.txt" },
    { path = "essays/essay61.txt", url="essays/essay61.txt", title="essay61.txt" },
    { path = "essays/essay62.txt", url="essays/essay62.txt", title="essay62.txt" },
    { path = "essays/essay63.txt", url="essays/essay63.txt", title="essay63.txt" },
    { path = "essays/essay64.txt", url="essays/essay64.txt", title="essay64.txt" },
    { path = "essays/essay65.txt", url="essays/essay65.txt", title="essay65.txt" },
    { path = "essays/essay66.txt", url="essays/essay66.txt", title="essay66.txt" },
    { path = "essays/essay67.txt", url="essays/essay67.txt", title="essay67.txt" },
    { path = "essays/essay68.txt", url="essays/essay68.txt", title="essay68.txt" },
    { path = "essays/essay69.txt", url="essays/essay69.txt", title="essay69.txt" },
    { path = "essays/essay70.txt", url="essays/essay70.txt", title="essay70.txt" },
    { path = "essays/essay71.txt", url="essays/essay71.txt", title="essay71.txt" },
    { path = "essays/essay72.txt", url="essays/essay72.txt", title="essay72.txt" },
    { path = "essays/essay73.txt", url="essays/essay73.txt", title="essay73.txt" },
    { path = "essays/essay74.txt", url="essays/essay74.txt", title="essay74.txt" },
    { path = "essays/essay75.txt", url="essays/essay75.txt", title="essay75.txt" },
    { path = "essays/essay76.txt", url="essays/essay76.txt", title="essay76.txt" },
    { path = "essays/essay77.txt", url="essays/essay77.txt", title="essay77.txt" },
    { path = "essays/essay78.txt", url="essays/essay78.txt", title="essay78.txt" },
    { path = "essays/essay79.txt", url="essays/essay79.txt", title="essay79.txt" },
    { path = "essays/essay80.txt", url="essays/essay80.txt", title="essay80.txt" },
    { path = "essays/essay81.txt", url="essays/essay81.txt", title="essay81.txt" },
    { path = "essays/essay82.txt", url="essays/essay82.txt", title="essay82.txt" },
    { path = "essays/essay83.txt", url="essays/essay83.txt", title="essay83.txt" },
    { path = "essays/essay84.txt", url="essays/essay84.txt", title="essay84.txt" },
    { path = "essays/essay85.txt", url="essays/essay85.txt", title="essay85.txt" },
]

[output]
filename = "dist/federalist.crane"
