[input]
base_directory = "test/essays"
files = [
    { path = "essays/essay01.txt", url="essays/essay01.txt", title="essay01.txt" },
    { path = "essays/essay02.txt", url="essays/essay02.txt", title="essay02.txt" },
    { path = "essays/essay03.txt", url="essays/essay03.txt", title="essay03.txt" },
    { path = "essays/essay04.txt", url="essays/essay04.txt", title="essay04.txt" },
    { path = "essays/essay05.txt", url="essays/essay05.txt", title="essay05.txt" },
    { path = "essays/essay06.txt", url="essays/essay06.txt", title="essay06.txt" },
    { path = "essays/essay07.txt", url="essays/essay07.txt", title="essay07.txt" },
    { path = "essays/essay08.txt", url="essays/essay08.txt", title="essay08.txt" },
    { path = "essays/essay09.txt", url="essays/essay09.txt", title="essay09.txt" },
    { path = "essays/essay10.txt", url="essays/essay10.txt", title="essay10.txt" },
    { path = "essays/essay11.txt", url="essays/essay11.txt", title="essay11.txt" },
    { path = "essays/essay12.txt", url="essays/essay12.txt", title="essay12.txt" },
    { path = "essays/essay13.txt", url="essays/essay13.txt", title="essay13.txt" },
    { path = "essays/essay14.txt", url="essays/essay14.txt", title="essay14.txt" },
    { path = "essays/essay15.txt", url="essays/essay15.txt", title="essay15.txt" },
    { path = "essays/essay16.txt", url="essays/essay16.txt", title="essay16.txt" },
    { path = "essays/essay17.txt", url="essays/essay17.txt", title="essay17.txt" },
    { path = "essays/essay18.txt", url="essays/essay18.txt", title="essay18.txt" },
    { path = "essays/essay19.txt", url="essays/essay19.txt", title="essay19.txt" },
    { path = "essays/essay20.txt", url="essays/essay20.txt", title="essay20.txt" },
]

[output]
filename = "dist/federalist.crane"
